### ISSUE TITLE
How to install lexnlp?

### ISSUE THREAD

**Issue by rnekrasov** [LexPredict/lexpredict-lexnlp#6]
System: Win10\Anaconda3\Python 3.6.

**Comment by alfasst** [comment]
Download the master.zip an extract it or use 'git clone. Change default directory to the folder. run python setup.py install

**Comment by mjbommar** [comment]
Thanks, @alfasst!

@rnekrasov, @alfasst , there's also a third way that applies equally on Windows as elsewhere:
```
> pip install https://github.com/LexPredict/lexpredict-lexnlp/archive/master.zip
```

Or, for a specific release/branch, e.g., `0.1.9`:
```
> pip install https://github.com/LexPredict/lexpredict-lexnlp/archive/0.1.9.zip
```

**Comment by ericlex** [comment]
Also - Please note that LexNLP does not work with Python 3.7, which is the current version of the Anaconda distribution as of this date, due to issues on scipy / sklearn dependencies. 

For Anaconda distributions, you can work around it using a Virtual Environment with Python 3.7:
`conda create -n py36 python=3.6`
`conda activate py36`
`pip install https://github.com/LexPredict/lexpredict-lexnlp/archive/master.zip`

**Comment by plutext** [comment]
To use python 3.6 (eg 3.6.8) safely alongside 3.7 on eg Arch or Manjaro, you can install pyenv, then:
```
pyenv install 3.6.8
pyenv local 3.6.8
python setup.py install
```

**Comment by rachhitgarg** [comment]
Failed to build scipy

**Comment by VenkateshDharavath** [comment]
Well, Time has passed, I'm trying to install lexnlp on my python-3.8 virtual environment. and it fails to build wheel for pandas. Please reopen this thread. Following is the link to the full log of installation process. [https://drive.google.com/file/d/1v9S7C9Ht0lwxffyiSTrcgncPASLWv2x6/view?usp=sharing](url)
Thanks.
