### ISSUE TITLE
How to use lexnlp?

### ISSUE THREAD

**Issue by alfasst** [LexPredict/lexpredict-lexnlp#7]
How LexNLP can be used? Which are the functions available?

**Comment by alfasst** [comment]
I just saw the documentation link: http://lexpredict-lexnlp.readthedocs.io/en/docs-0.1.6/ Thanks

**Comment by mjbommar** [comment]
@alfasst , we will also be releasing updated documentation in the upcoming release with more complete coverage and additional examples.  Look for a new GitHub repository soon.

**Comment by RabbitJackTrade** [comment]
mjbommar,

I know the issue is closed, but I wonder if you have a general idea as to when the new GitHub repository is available? I'm really, really, interested in playing with Lexnlp, but I'd rather wait for the most recent version.

Additionally, if the new version could also contain a tutorial (preferably in a jupyter notebook) that would be great!

**Comment by rizwan92** [comment]
i find no documentation over how to train lex NLP with our custom data aset
